services:
  backend:
    build: ./DigitalSignature
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./DigitalSignatureFront
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
