services:
  backend:
    build: ./DigitalSignature
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    hostname: backend # Adicione esta linha

  frontend:
    build: ./DigitalSignatureFront
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge