spring:
    application:
      name: digitalsign
    servlet:
      multipart:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
